### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by DinuWije** [uwblueprint/starter-code-v2#85]
**TODO**:

- [x]  Python backend: rename reset_password route → resetPassword
- [ ]  Python backend: create default instance of EmailService
- [ ]  Python backend: create separate EntityRequestDTO and EntityResponseDTO
- [x]  Python backend: fix authorization decorator on entity routes ("Users" → "Users", "Admin")
- [ ]  Python backend: reorganize `resources` folder
- [ ]  TypeScript backend: reorganize type declarations
- [ ]  TypeScript backend: create default instance of EmailService
- [ ]  ~~TypeScript backend: log message format, include file and line number~~
- [ ]  TypeScript backend: Sequelize update return previous value bug
- [ ]  ALL: file naming consistency
- [ ]  ALL: class naming consistency
- [ ]  Frontend: move GraphQL login try catch to component
- [ ]  CLI: compatibility issues (OS and different terminals)
- [ ]  Move shared test data to separate file
